"""Canonical one-click showcase pipeline for detection and prediction."""

from __future__ import annotations

import json
import os
import time
from pathlib import Path

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

BASE_PATH = Path(__file__).resolve().parent.parent
ACTIVE_DIR = BASE_PATH / "seizure_detection"
DETECTION_OUTPUT_DIR = ACTIVE_DIR / "outputs"
PREDICTION_OUTPUT_DIR = BASE_PATH / "prediction_outputs_local"
SHOWCASE_DIR = BASE_PATH / "showcase_outputs"
PIPELINE_VERSION = "edge_safe_patched_dual_stream_tsmixer_v15_dsp_session_norm"


def _env_int(name: str, default: int) -> int:
    try:
        return int(os.environ.get(name, str(default)))
    except ValueError:
        return default


def _env_float(name: str, default: float) -> float:
    try:
        return float(os.environ.get(name, str(default)))
    except ValueError:
        return default


def format_elapsed(seconds: float) -> str:
    """Format elapsed seconds as a compact human-readable duration."""
    seconds = int(round(seconds))
    hours, remainder = divmod(seconds, 3600)
    minutes, seconds = divmod(remainder, 60)
    if hours:
        return f"{hours}h {minutes}m {seconds}s"
    if minutes:
        return f"{minutes}m {seconds}s"
    return f"{seconds}s"


def timed_step(label: str, func, *args, **kwargs):
    """Run a pipeline step and print its elapsed time."""
    start = time.perf_counter()
    print(f"\n[{label}] Started at {time.strftime('%Y-%m-%d %H:%M:%S')}")
    try:
        return func(*args, **kwargs)
    finally:
        elapsed = time.perf_counter() - start
        print(f"[{label}] Finished in {format_elapsed(elapsed)}")


def run_detection_pipeline() -> None:
    from phase4_validation import main as detection_main

    print("\n" + "=" * 70)
    print("PHASE A: Detection Upsell Pipeline")
    print("=" * 70)
    detection_main()


def run_prediction_pipeline() -> None:
    from run_local import run_pipeline as prediction_run

    print("\n" + "=" * 70)
    print("PHASE B: Prediction Horizon Pipeline")
    print("=" * 70)
    prediction_run()


def load_json(path: Path) -> dict:
    with path.open("r", encoding="utf-8") as file_handle:
        return json.load(file_handle)


def valid_detection_results(path: Path) -> bool:
    """Return True only for results generated by the leakage-safe pipeline."""
    if not path.exists():
        return False
    try:
        results = load_json(path)
    except Exception:
        return False
    sensor_policy = results.get("sensor_policy", {})
    label_policy = results.get("label_policy", {})
    run_config = results.get("run_config", {})
    provenance = results.get("model_provenance", {})
    variant_paths = [
        item.get("checkpoint_path")
        for item in provenance.get("variants", {}).values()
        if isinstance(item, dict)
    ]
    checkpoints_present = bool(variant_paths) and all(
        Path(path).exists() for path in variant_paths if path
    )
    expected_window_seconds = _env_float("DETECTION_WINDOW_SECONDS", 5.0)
    expected_stride_seconds = (
        _env_int(
            "DETECTION_STRIDE",
            int(round(expected_window_seconds * 32)),
        )
        / 32.0
    )
    expected_max_sessions = _env_int("DETECTION_MAX_SESSIONS", 80)
    return (
        results.get("pipeline_version") == PIPELINE_VERSION
        and results.get("status") == "completed"
        and results.get("split_strategy") == "patient-level held-out split"
        and sensor_policy.get("synthetic_signals") is False
        and isinstance(results.get("product_allocation_selection"), dict)
        and isinstance(results.get("best_science_model"), dict)
        and isinstance(results.get("best_product_model"), dict)
        and isinstance(results.get("matched_false_alarm_operating_point"), dict)
        and label_policy.get("seizure_duration_seconds")
        == _env_int("SEIZURE_DURATION_SECONDS", 300)
        and label_policy.get("merge_gap_seconds")
        == _env_int("SEIZURE_MERGE_GAP_SECONDS", 0)
        and abs(
            float(label_policy.get("detection_window_seconds", -1.0))
            - expected_window_seconds
        )
        < 1e-6
        and abs(
            float(label_policy.get("detection_stride_seconds", -1.0))
            - expected_stride_seconds
        )
        < 1e-6
        and run_config.get("selected_session_count") == expected_max_sessions
        and (
            provenance.get("retrained_from_scratch_all_variants") is True
            or checkpoints_present
        )
    )


def valid_prediction_results(path: Path) -> bool:
    """Return True only for session-held-out prediction reports."""
    if not path.exists():
        return False
    try:
        results = load_json(path)
    except Exception:
        return False
    dataset_usage = results.get("dataset_usage", {})
    full_counts = dataset_usage.get("full_dataset_counts", {})
    expected_sessions = _env_int("PREDICTION_MAX_SESSIONS", 40)
    train_sessions = results.get("train_sessions", [])
    val_sessions = results.get("val_sessions", [])
    metrics = results.get("metrics", {})
    return (
        results.get("pipeline_version") == PIPELINE_VERSION
        and results.get("status") == "completed"
        and results.get("split_strategy") == "patient-level held-out split"
        and isinstance(metrics, dict)
        and len(train_sessions) + len(val_sessions) == expected_sessions
        and dataset_usage.get("final_metrics_use_full_validation") is True
        and full_counts.get("val_sequences") is not None
        and all(
            isinstance(metrics.get(str(horizon)), dict)
            and metrics[str(horizon)].get("evaluation_split") == "full_validation"
            and metrics[str(horizon)].get("n_val") == full_counts.get("val_sequences")
            for horizon in (300, 900, 1800)
        )
    )


def build_detection_summary(results: dict) -> Path:
    summary_dir = SHOWCASE_DIR / "detection"
    summary_dir.mkdir(parents=True, exist_ok=True)

    standard = results.get("standard_mode", {})
    pro = results.get("pro_mode", {})

    metrics = ["recall", "precision", "f1", "pr_auc", "auc", "balanced_accuracy"]
    standard_values = [float(standard.get(metric, 0.0)) for metric in metrics]
    pro_values = [float(pro.get(metric, 0.0)) for metric in metrics]

    x = np.arange(len(metrics))
    width = 0.35

    fig, ax = plt.subplots(figsize=(10, 6))
    ax.bar(
        x - width / 2,
        standard_values,
        width,
        label="Standard / Watch Only",
        color="#6C757D",
    )
    ax.bar(
        x + width / 2, pro_values, width, label="Pro / Add-on Sensors", color="#2E86AB"
    )
    ax.set_xticks(x)
    ax.set_xticklabels([name.upper().replace("_", "-") for name in metrics])
    ax.set_ylim(0, 1)
    ax.set_ylabel("Score")
    ax.set_title("Detection Quality Metrics")
    ax.legend()
    ax.grid(axis="y", alpha=0.25)

    output_path = summary_dir / "detection_comparison.png"
    fig.tight_layout()
    fig.savefig(output_path, dpi=300, bbox_inches="tight")
    plt.close(fig)

    matched = results.get("matched_false_alarm_operating_point", {})
    if isinstance(matched, dict) and matched.get("standard") and matched.get("pro"):
        matched_metrics = [
            "recall",
            "precision",
            "f1",
            "balanced_accuracy",
            "false_alarms_per_hour",
        ]
        standard_matched = matched["standard"]
        pro_matched = matched["pro"]
        standard_matched_values = [
            float(standard_matched.get(metric, 0.0)) for metric in matched_metrics
        ]
        pro_matched_values = [
            float(pro_matched.get(metric, 0.0)) for metric in matched_metrics
        ]

        fig, axes = plt.subplots(1, 2, figsize=(12, 5))
        score_metrics = matched_metrics[:4]
        score_x = np.arange(len(score_metrics))
        axes[0].bar(
            score_x - width / 2,
            standard_matched_values[:4],
            width,
            label="Standard",
            color="#6C757D",
        )
        axes[0].bar(
            score_x + width / 2,
            pro_matched_values[:4],
            width,
            label="Pro",
            color="#2E86AB",
        )
        axes[0].set_xticks(score_x)
        axes[0].set_xticklabels(
            [name.upper().replace("_", "-") for name in score_metrics]
        )
        axes[0].set_ylim(0, 1)
        axes[0].set_ylabel("Score")
        axes[0].set_title("Matched Alarm Budget Metrics")
        axes[0].legend()
        axes[0].grid(axis="y", alpha=0.25)

        axes[1].bar(
            ["Standard", "Pro"],
            [standard_matched_values[4], pro_matched_values[4]],
            color=["#6C757D", "#2E86AB"],
        )
        axes[1].set_ylabel("False alarms / hour")
        axes[1].set_title("Held-Out Test Alarm Burden")
        axes[1].grid(axis="y", alpha=0.25)

        matched_path = summary_dir / "detection_matched_alarm_budget.png"
        fig.tight_layout()
        fig.savefig(matched_path, dpi=300, bbox_inches="tight")
        plt.close(fig)
    with (summary_dir / "detection_summary.json").open(
        "w", encoding="utf-8"
    ) as file_handle:
        json.dump(results, file_handle, indent=2)
    return output_path


def _fmt_metric(value, digits: int = 4) -> str:
    try:
        value = float(value)
    except (TypeError, ValueError):
        return "n/a"
    if np.isnan(value):
        return "n/a"
    return f"{value:.{digits}f}"


def build_release_summary(
    detection_results: dict | None, prediction_results: dict | None
) -> Path:
    """Write a release summary from the latest artifacts."""
    lines = [
        "# GTC Seizure Event Detection Release Report",
        "",
        "Release: v1.0",
        f"Generated: {time.strftime('%Y-%m-%d %H:%M:%S')}",
        "",
        "## Product Configuration",
        "",
        (
            "Standard is the low-cost configuration and uses ACC as the required "
            "base sensor plus the selected base optional sensor. Pro is cumulative: "
            "it keeps the Standard signals and adds a second sensor module with "
            "required PPG plus the selected add-on optional sensor. The PPG stream "
            "contributes BVP and HR features. IBI is excluded from model inputs "
            "because several source files are empty or malformed."
        ),
    ]

    if detection_results:
        standard = detection_results.get("standard_mode", {})
        pro = detection_results.get("pro_mode", {})
        allocation_selection = detection_results.get("product_allocation_selection", {})
        selected_allocation = allocation_selection.get("selected_allocation", {})
        selected_allocation_name = allocation_selection.get(
            "selected_allocation_name", "n/a"
        )
        selected_variant = detection_results.get("pro_model_selection", {}).get(
            "selected_variant", "n/a"
        )
        selected_standard_variant = detection_results.get(
            "standard_model_selection", {}
        ).get("selected_variant", "n/a")
        pro_features = pro.get("enabled_secondary_features", [])
        standard_features = standard.get("enabled_secondary_features", [])
        matched = detection_results.get("matched_false_alarm_operating_point", {})

        lines.extend(
            [
                "",
                "## Detection Result",
                "",
                (
                    f"- Evaluation split: {detection_results.get('split_strategy', 'n/a')}; "
                    f"train {detection_results.get('split_audit', {}).get('train', {}).get('sessions', 'n/a')} sessions, "
                    f"validation {detection_results.get('split_audit', {}).get('val', {}).get('sessions', 'n/a')}, "
                    f"test {detection_results.get('split_audit', {}).get('test', {}).get('sessions', 'n/a')}."
                ),
                (
                    f"- Selected allocation: {selected_allocation_name}; Standard optional sensors "
                    f"{selected_allocation.get('base_optional', [])}, Pro add-on optional sensors "
                    f"{selected_allocation.get('addon_optional', [])}."
                ),
                (
                    f"- Standard model: {selected_standard_variant}; secondary features {standard_features}; "
                    f"AUC {_fmt_metric(standard.get('auc'))}, PR-AUC {_fmt_metric(standard.get('pr_auc'))}, "
                    f"recall {_fmt_metric(standard.get('recall'))}, "
                    f"event sensitivity {_fmt_metric(standard.get('event_level', {}).get('event_sensitivity'))}, "
                    f"balanced accuracy {_fmt_metric(standard.get('balanced_accuracy'))}, "
                    f"false alarms/hour {_fmt_metric(standard.get('false_alarms_per_hour'), 2)}."
                ),
                (
                    f"- Pro model: {selected_variant}; secondary features {pro_features}; "
                    f"AUC {_fmt_metric(pro.get('auc'))}, PR-AUC {_fmt_metric(pro.get('pr_auc'))}, "
                    f"recall {_fmt_metric(pro.get('recall'))}, "
                    f"event sensitivity {_fmt_metric(pro.get('event_level', {}).get('event_sensitivity'))}, "
                    f"balanced accuracy {_fmt_metric(pro.get('balanced_accuracy'))}, "
                    f"false alarms/hour {_fmt_metric(pro.get('false_alarms_per_hour'), 2)}."
                ),
                (
                    f"- Raw accuracy is diagnostic only: seizure-window prevalence is "
                    f"{_fmt_metric(standard.get('positive_rate'))}; an all-normal classifier would score "
                    f"{_fmt_metric(standard.get('all_normal_baseline_accuracy'))} accuracy while detecting no events."
                ),
                (
                    f"- Pro AUC improvement over Standard: "
                    f"{_fmt_metric(float(pro.get('auc', 0)) - float(standard.get('auc', 0)))}; "
                    f"recall improvement: "
                    f"{_fmt_metric(float(pro.get('recall', 0)) - float(standard.get('recall', 0)))}."
                ),
            ]
        )
        fusion = pro.get("score_fusion", {})
        if fusion:
            lines.append(
                "- Pro score fusion: validation-selected add-on model weight "
                f"{_fmt_metric(fusion.get('pro_model_weight'))}; remaining weight "
                "comes from the Standard detector score."
            )

        if isinstance(matched, dict) and matched.get("standard") and matched.get("pro"):
            matched_standard = matched["standard"]
            matched_pro = matched["pro"]
            fixed_budgets = matched.get("fixed_validation_alarm_budgets", {})
            lines.extend(
                [
                    "",
                    "### Matched False-Alarm Operating Point",
                    "",
                    (
                        f"- Validation alarm budget: "
                        f"{_fmt_metric(matched.get('standard_validation_false_alarms_per_hour'), 2)} false alarms/hour."
                    ),
                    (
                        f"- Test recall: Standard {_fmt_metric(matched_standard.get('recall'))} -> "
                        f"Pro {_fmt_metric(matched_pro.get('recall'))}."
                    ),
                    (
                        f"- Event sensitivity: Standard "
                        f"{_fmt_metric(matched_standard.get('event_level', {}).get('event_sensitivity'))} -> "
                        f"Pro {_fmt_metric(matched_pro.get('event_level', {}).get('event_sensitivity'))}."
                    ),
                    (
                        f"- Test false alarms/hour: Standard "
                        f"{_fmt_metric(matched_standard.get('false_alarms_per_hour'), 2)} -> "
                        f"Pro {_fmt_metric(matched_pro.get('false_alarms_per_hour'), 2)}."
                    ),
                ]
            )
            if isinstance(fixed_budgets, dict):
                standard_grid = fixed_budgets.get("standard", {})
                pro_grid = fixed_budgets.get("pro", {})
                budget_lines = []
                for budget in fixed_budgets.get("budgets_per_hour", []):
                    key = str(budget)
                    if key not in standard_grid or key not in pro_grid:
                        key = str(float(budget))
                    if key not in standard_grid or key not in pro_grid:
                        continue
                    std_budget = standard_grid[key]
                    pro_budget = pro_grid[key]
                    std_event = std_budget.get("event_level", {})
                    pro_event = pro_budget.get("event_level", {})
                    event_text = ""
                    if std_event and pro_event:
                        event_text = (
                            f"; event sensitivity "
                            f"{_fmt_metric(std_event.get('event_sensitivity'))} -> "
                            f"{_fmt_metric(pro_event.get('event_sensitivity'))}"
                        )
                    budget_lines.append(
                        f"- {float(budget):g} false alarms/hour validation budget: "
                        f"recall {_fmt_metric(std_budget.get('recall'))} -> "
                        f"{_fmt_metric(pro_budget.get('recall'))}; "
                        f"test false alarms/hour "
                        f"{_fmt_metric(std_budget.get('false_alarms_per_hour'), 2)} -> "
                        f"{_fmt_metric(pro_budget.get('false_alarms_per_hour'), 2)}"
                        f"{event_text}."
                    )
                if budget_lines:
                    lines.extend(
                        [
                            "",
                            "### Fixed Alarm-Budget Grid",
                            "",
                            *budget_lines,
                        ]
                    )
        interpretationParts = [
            (
                "Interpretation: seizure windows are rare, so raw accuracy is not a "
                "sufficient success metric. AUC, recall, balanced accuracy, and alarm "
                "burden should be read alongside the confusion matrix."
            )
        ]
        if matched and isinstance(matched, dict):
            matchedStandard = matched.get("standard", {})
            matchedPro = matched.get("pro", {})
            proRecallGain = float(matchedPro.get("recall", 0.0)) - float(
                matchedStandard.get("recall", 0.0)
            )
            proAlarmGain = float(matchedPro.get("false_alarms_per_hour", 0.0)) - float(
                matchedStandard.get("false_alarms_per_hour", 0.0)
            )
            aucGain = float(pro.get("auc", 0.0)) - float(standard.get("auc", 0.0))
            tradeoffs = []
            tradeoffs.append(
                f"Pro ROC-AUC is {'higher' if aucGain >= 0 else 'lower'} "
                f"({_fmt_metric(aucGain)} difference)."
            )
            if abs(proRecallGain) < 1e-12:
                recallText = "equal"
            else:
                recallText = "higher" if proRecallGain > 0 else "lower"
            tradeoffs.append(
                f"Pro recall is {recallText} "
                f"({_fmt_metric(proRecallGain)} difference)."
            )
            if abs(proAlarmGain) < 1e-12:
                alarmText = "equal"
            else:
                alarmText = "higher" if proAlarmGain > 0 else "lower"
            tradeoffs.append(
                f"Pro false alarms/hour are {alarmText} "
                f"({_fmt_metric(proAlarmGain, 2)} difference)."
            )
            interpretationParts.append(" ".join(tradeoffs))
        lines.extend(["", " ".join(interpretationParts)])
    if prediction_results:
        lines.extend(["", "## Experimental Pre-Ictal Risk Result", ""])
        dataset_usage = prediction_results.get("dataset_usage", {})
        eval_usage = dataset_usage.get("final_metric_evaluation", {})
        if eval_usage:
            lines.append(
                f"- Final metrics evaluated on: {eval_usage.get('strategy', 'n/a')} "
                f"({eval_usage.get('selected_sequences', 'n/a')} sequences)."
            )
        for horizon in ("300", "900", "1800"):
            metric = prediction_results.get("metrics", {}).get(horizon, {})
            calibrated = metric.get("calibrated_threshold_metrics", {})
            top_risk = metric.get("top_risk_metrics", {}).get("top_5pct", {})
            minutes = int(horizon) // 60
            lines.append(
                f"- Horizon {minutes} min: AUC {_fmt_metric(metric.get('auc'))}; "
                f"calibrated F1 {_fmt_metric(calibrated.get('f1'))}; "
                f"calibrated recall {_fmt_metric(calibrated.get('recall'))}; "
                f"top-5% risk recall {_fmt_metric(top_risk.get('recall'))}."
            )
        lines.extend(
            [
                "",
                (
                    "This section is future-work output, not part of the current "
                    "detection claim. It is reported as risk ranking because "
                    "pre-ictal positives are sparse. AUC, calibrated operating "
                    "points, and top-risk capture are more informative than fixed "
                    "0.5 threshold precision/recall."
                ),
            ]
        )
        lines.extend(
            [
                "",
                "## Validation Scope",
                "",
                (
                    f"- Claim scope: {detection_results.get('claim_scope', 'n/a')}."
                ),
                "- The pipeline uses real Empatica signals, session-held-out splits, train-only normalization, and no synthetic label-derived features.",
                "- The reported scope is personalized/session-level validation on the available Mayo recordings.",
                "- Patient-independent validation, improved event-level seizure sensitivity, prospective clinical evaluation, and physical hardware deployment are outside the v1.0 scope.",
            "",
            "## Key Artifacts",
            "",
            "- Detection results: seizure_detection/outputs/results.json",
            "- Matched alarm chart: showcase_outputs/detection/detection_matched_alarm_budget.png",
            "- Detection chart: showcase_outputs/detection/detection_comparison.png",
            "- Pro TFLite model: seizure_detection/outputs/seizure_model.tflite",
            "- Standard TFLite model: seizure_detection/outputs/seizure_model_standard.tflite",
        ]
    )
    if prediction_results:
        lines.extend(
            [
                "- Experimental risk results: prediction_outputs_local/metrics.json",
                "- Experimental risk dashboard: showcase_outputs/prediction/executive_dashboard.png",
            ]
        )

    summary_path = SHOWCASE_DIR / "RELEASE_REPORT.md"
    summary_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return summary_path


def build_prediction_summary(metrics: dict) -> Path:
    summary_dir = SHOWCASE_DIR / "prediction"
    summary_dir.mkdir(parents=True, exist_ok=True)

    metrics_payload = metrics.get("metrics", metrics)

    y_true_dict = {}
    y_pred_dict = {}
    y_prob_dict = {}

    for horizon in (300, 900, 1800):
        predictions_path = PREDICTION_OUTPUT_DIR / f"predictions_{horizon}.csv"
        if not predictions_path.exists():
            continue
        frame = pd.read_csv(predictions_path)
        y_true = frame["y_true"].to_numpy()
        probability_column = "y_prob" if "y_prob" in frame.columns else "y_pred"
        y_prob = frame[probability_column].to_numpy()
        y_pred = (y_prob >= 0.5).astype(int)

        y_true_dict[horizon] = y_true
        y_pred_dict[horizon] = y_pred
        y_prob_dict[horizon] = y_prob
    metrics_dict = {int(k): v for k, v in metrics_payload.items()}
    with (summary_dir / "prediction_summary.json").open(
        "w", encoding="utf-8"
    ) as file_handle:
        json.dump(metrics_dict, file_handle, indent=2)
    if not y_true_dict:
        note_path = summary_dir / "prediction_summary_note.txt"
        status = metrics.get("status", "unknown")
        reason = metrics.get("reason", "prediction CSV files were not available")
        note_path.write_text(
            f"Prediction status: {status}\n"
            f"Reason: {reason}\n"
            "Prediction metrics were saved, but no prediction CSV files were available "
            "for visualization.\n",
            encoding="utf-8",
        )
        return note_path
    from prediction_visualizations import save_all_visualizations

    save_all_visualizations(
        y_true_dict, y_pred_dict, y_prob_dict, metrics_dict, str(summary_dir)
    )
    return summary_dir / "executive_dashboard.png"


def main() -> None:
    total_start = time.perf_counter()
    os.makedirs(SHOWCASE_DIR, exist_ok=True)

    force = os.environ.get("FORCE_RERUN", "0") == "1"
    run_prediction = os.environ.get("SKIP_PREDICTION", "0") != "1"
    if force:
        os.environ["DETECTION_FORCE_RETRAIN_VARIANTS"] = "1"
        os.environ.setdefault("PREDICTION_EVALUATE_FULL_VAL", "1")
    detection_results_path = DETECTION_OUTPUT_DIR / "results.json"
    prediction_metrics_path = PREDICTION_OUTPUT_DIR / "metrics.json"

    if force or not valid_detection_results(detection_results_path):
        timed_step("Detection pipeline", run_detection_pipeline)
    else:
        print("\nSkipping detection stage; existing results found.")
    if run_prediction:
        if force or not valid_prediction_results(prediction_metrics_path):
            timed_step("Prediction pipeline", run_prediction_pipeline)
        else:
            print("\nSkipping prediction stage; existing results found.")
    else:
        print("\nSkipping prediction stage because SKIP_PREDICTION=1.")
    if detection_results_path.exists():
        detection_results = load_json(detection_results_path)
        detection_chart = timed_step(
            "Detection summary", build_detection_summary, detection_results
        )
        print(f"Detection summary saved to: {detection_chart}")
    else:
        print(f"Detection results not found: {detection_results_path}")
    if run_prediction and prediction_metrics_path.exists():
        prediction_metrics = load_json(prediction_metrics_path)
        prediction_chart = timed_step(
            "Prediction summary", build_prediction_summary, prediction_metrics
        )
        print(f"Prediction summary saved to: {prediction_chart}")
    elif run_prediction:
        print(f"Prediction metrics not found: {prediction_metrics_path}")
    else:
        print("Prediction summary skipped.")
    detection_for_summary = (
        load_json(detection_results_path) if detection_results_path.exists() else None
    )
    prediction_for_summary = (
        load_json(prediction_metrics_path)
        if run_prediction and prediction_metrics_path.exists()
        else None
    )
    summary_path = timed_step(
        "Release report",
        build_release_summary,
        detection_for_summary,
        prediction_for_summary,
    )
    print(f"Release report saved to: {summary_path}")

    print("\n" + "=" * 70)
    print("SHOWCASE COMPLETE")
    print("=" * 70)
    print(f"Outputs: {SHOWCASE_DIR}")
    print(f"Total elapsed: {format_elapsed(time.perf_counter() - total_start)}")


if __name__ == "__main__":
    main()
